

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-web-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      healthcheck:
  test: ["CMD", "wget", "-q", "-O-", "http://127.0.0.1:3000/"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
